//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpScanner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultTtsLang {
            get {
                return ((string)(this["DefaultTtsLang"]));
            }
            set {
                this["DefaultTtsLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TÜRKÇE")]
        public string DefaultLang {
            get {
                return ((string)(this["DefaultLang"]));
            }
            set {
                this["DefaultLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatabaseFile {
            get {
                return ((string)(this["DatabaseFile"]));
            }
            set {
                this["DatabaseFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public int DefaultThumbNailDpi {
            get {
                return ((int)(this["DefaultThumbNailDpi"]));
            }
            set {
                this["DefaultThumbNailDpi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ButtonScanMode {
            get {
                return ((int)(this["ButtonScanMode"]));
            }
            set {
                this["ButtonScanMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFirstRun {
            get {
                return ((bool)(this["IsFirstRun"]));
            }
            set {
                this["IsFirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WatchFolderPdfFileChange {
            get {
                return ((bool)(this["WatchFolderPdfFileChange"]));
            }
            set {
                this["WatchFolderPdfFileChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PreviewIndex {
            get {
                return ((int)(this["PreviewIndex"]));
            }
            set {
                this["PreviewIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedFtp {
            get {
                return ((string)(this["SelectedFtp"]));
            }
            set {
                this["SelectedFtp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegisterBatchWatcher {
            get {
                return ((bool)(this["RegisterBatchWatcher"]));
            }
            set {
                this["RegisterBatchWatcher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BatchFolder {
            get {
                return ((string)(this["BatchFolder"]));
            }
            set {
                this["BatchFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DirectOpenEypFile {
            get {
                return ((bool)(this["DirectOpenEypFile"]));
            }
            set {
                this["DirectOpenEypFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DirectOpenPdfFile {
            get {
                return ((bool)(this["DirectOpenPdfFile"]));
            }
            set {
                this["DirectOpenPdfFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DirectOpenUdfFile {
            get {
                return ((bool)(this["DirectOpenUdfFile"]));
            }
            set {
                this["DirectOpenUdfFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DirectlyOverwriteCompressedPdf {
            get {
                return ((bool)(this["DirectlyOverwriteCompressedPdf"]));
            }
            set {
                this["DirectlyOverwriteCompressedPdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n                <ArrayOfString xmlns:xsd" +
            "=\"http://www.w3.org/2001/XMLSchema\"\r\n                xmlns:xsi=\"http://www.w3.or" +
            "g/2001/XMLSchema-instance\" />\r\n            ")]
        public global::System.Collections.Specialized.StringCollection PatchCodes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PatchCodes"]));
            }
            set {
                this["PatchCodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n                <ArrayOfString xmlns:xsd" +
            "=\"http://www.w3.org/2001/XMLSchema\"\r\n                xmlns:xsi=\"http://www.w3.or" +
            "g/2001/XMLSchema-instance\" />\r\n            ")]
        public global::System.Collections.Specialized.StringCollection FtpSites {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FtpSites"]));
            }
            set {
                this["FtpSites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ProcessorCount {
            get {
                return ((int)(this["ProcessorCount"]));
            }
            set {
                this["ProcessorCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SharePointUrl {
            get {
                return ((string)(this["SharePointUrl"]));
            }
            set {
                this["SharePointUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SharePointLibraryName {
            get {
                return ((string)(this["SharePointLibraryName"]));
            }
            set {
                this["SharePointLibraryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SharePointUserName {
            get {
                return ((string)(this["SharePointUserName"]));
            }
            set {
                this["SharePointUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SharePointUserPassword {
            get {
                return ((string)(this["SharePointUserPassword"]));
            }
            set {
                this["SharePointUserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckAppUpdate {
            get {
                return ((bool)(this["CheckAppUpdate"]));
            }
            set {
                this["CheckAppUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int UpdateInterval {
            get {
                return ((int)(this["UpdateInterval"]));
            }
            set {
                this["UpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastCheckDate {
            get {
                return ((global::System.DateTime)(this["LastCheckDate"]));
            }
            set {
                this["LastCheckDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContributionIsImageMode {
            get {
                return ((bool)(this["ContributionIsImageMode"]));
            }
            set {
                this["ContributionIsImageMode"] = value;
            }
        }
    }
}
