//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwainControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwainControl.Properties.Resources.ja", typeof(Resources_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細はこちら.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルに
        ///ドキュメントを添付してください.
        /// </summary>
        public static string ADDDOC {
            get {
                return ResourceManager.GetString("ADDDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCRデータを保存.
        /// </summary>
        public static string ADDOCRTODB {
            get {
                return ResourceManager.GetString("ADDOCRTODB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to これがチェックされている場合、下にマークされた文書は、左側のアクティブな文書のテキストとしてデータベースに保存されます。.
        /// </summary>
        public static string ADDOCRTOOLTIP {
            get {
                return ResourceManager.GetString("ADDOCRTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドキュメントフィーダー.
        /// </summary>
        public static string ADF {
            get {
                return ResourceManager.GetString("ADF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全員だ.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンテンツのコピーを許可します.
        /// </summary>
        public static string ALLOWCOPY {
            get {
                return ResourceManager.GetString("ALLOWCOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドキュメントの編集を許可します。.
        /// </summary>
        public static string ALLOWEDIT {
            get {
                return ResourceManager.GetString("ALLOWEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印刷させてください.
        /// </summary>
        public static string ALLOWPRINT {
            get {
                return ResourceManager.GetString("ALLOWPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このアプリケーションは、スキャンとドキュメントの追跡を容易にするために開発されました。.
        /// </summary>
        public static string APPDESC {
            get {
                return ResourceManager.GetString("APPDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申し込み.
        /// </summary>
        public static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 色を適用.
        /// </summary>
        public static string APPLYCOLOR {
            get {
                return ResourceManager.GetString("APPLYCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アプリは既に実行されています.
        /// </summary>
        public static string APPRUNNING {
            get {
                return ResourceManager.GetString("APPRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動保存フォルダを指定します。!.
        /// </summary>
        public static string AUTOFOLDER {
            get {
                return ResourceManager.GetString("AUTOFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動保存パスが変更されました。古いファイルは新しいフォルダに移動されません。.
        /// </summary>
        public static string AUTOFOLDERCHANGE {
            get {
                return ResourceManager.GetString("AUTOFOLDERCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動
        ///保存.
        /// </summary>
        public static string AUTOPATH {
            get {
                return ResourceManager.GetString("AUTOPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オートピクチャー.
        /// </summary>
        public static string AutoPicture {
            get {
                return ResourceManager.GetString("AutoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動回転.
        /// </summary>
        public static string AUTOROTATE {
            get {
                return ResourceManager.GetString("AUTOROTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動テキスト.
        /// </summary>
        public static string AutoText {
            get {
                return ResourceManager.GetString("AutoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共同作業.
        /// </summary>
        public static string BATCH {
            get {
                return ResourceManager.GetString("BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下のフォルダに画像ファイルを追加すると、プログラムを開いている限り、同じフォルダ内で自動的にPDFファイルに変換されます.
        /// </summary>
        public static string BATCHDESC {
            get {
                return ResourceManager.GetString("BATCHDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動エッジ検出.
        /// </summary>
        public static string BORDERDETECT {
            get {
                return ResourceManager.GetString("BORDERDETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 黒と白.
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カレンダー.
        /// </summary>
        public static string CALENDAR {
            get {
                return ResourceManager.GetString("CALENDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カメラ.
        /// </summary>
        public static string CAMERA {
            get {
                return ResourceManager.GetString("CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リストをクリア.
        /// </summary>
        public static string CLEARLIST {
            get {
                return ResourceManager.GetString("CLEARLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パソコンを消せ.
        /// </summary>
        public static string CLOSECOMP {
            get {
                return ResourceManager.GetString("CLOSECOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カラフル.
        /// </summary>
        public static string COLOR {
            get {
                return ResourceManager.GetString("COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to しきい値を設定した後にこれをクリックすると、2 番目の色の選択を行うことができます。.
        /// </summary>
        public static string COLORCHANGETIP {
            get {
                return ResourceManager.GetString("COLORCHANGETIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圧縮する.
        /// </summary>
        public static string COMPRESS {
            get {
                return ResourceManager.GetString("COMPRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドリンクを読もう.
        /// </summary>
        public static string CONTENT {
            get {
                return ResourceManager.GetString("CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TesseractとleptonicaのバイナリはVisual Studio 2019でコンパイルされているため、Visual Studio 2019 Runtimeがインストールされていることを確認する必要があります。.
        /// </summary>
        public static string CRUNTIME {
            get {
                return ResourceManager.GetString("CRUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [日].
        /// </summary>
        public static string DAY {
            get {
                return ResourceManager.GetString("DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デフォルト.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スキャンしないでください.
        /// </summary>
        public static string DEFAULTSCANNAME {
            get {
                return ResourceManager.GetString("DEFAULTSCANNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 曲線を修正してください.
        /// </summary>
        public static string DESKEW {
            get {
                return ResourceManager.GetString("DESKEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象.
        /// </summary>
        public static string DESTLANG {
            get {
                return ResourceManager.GetString("DESTLANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書類作成.
        /// </summary>
        public static string DOCUMENT {
            get {
                return ResourceManager.GetString("DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テキストを描く.
        /// </summary>
        public static string DRAWTEXT {
            get {
                return ResourceManager.GetString("DRAWTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ターゲットカラー.
        /// </summary>
        public static string DSTCOLOR {
            get {
                return ResourceManager.GetString("DSTCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空白ページをスキップ.
        /// </summary>
        public static string EMPTYPAGE {
            get {
                return ResourceManager.GetString("EMPTYPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗号化.
        /// </summary>
        public static string ENCRYPT {
            get {
                return ResourceManager.GetString("ENCRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyp ファイルを直接開く.
        /// </summary>
        public static string EYPOPEN {
            get {
                return ResourceManager.GetString("EYPOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クイック
        ///スキャン.
        /// </summary>
        public static string FASTSCAN {
            get {
                return ResourceManager.GetString("FASTSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クイックスキャンが完了した後に実行するアクション.
        /// </summary>
        public static string FASTSCANAFTER {
            get {
                return ResourceManager.GetString("FASTSCANAFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルは？.
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名:!.
        /// </summary>
        public static string FILENAME {
            get {
                return ResourceManager.GetString("FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FIX {
            get {
                return ResourceManager.GetString("FIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フラットベッド.
        /// </summary>
        public static string FLATBED {
            get {
                return ResourceManager.GetString("FLATBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォント.
        /// </summary>
        public static string FONT {
            get {
                return ResourceManager.GetString("FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グラフィック.
        /// </summary>
        public static string GRAPH {
            get {
                return ResourceManager.GetString("GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グレイ.
        /// </summary>
        public static string GRAY {
            get {
                return ResourceManager.GetString("GRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インターフェースを表示.
        /// </summary>
        public static string GUI {
            get {
                return ResourceManager.GetString("GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GUID].
        /// </summary>
        public static string GUID {
            get {
                return ResourceManager.GetString("GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高さの数.
        /// </summary>
        public static string HEIGHTCOUNT {
            get {
                return ResourceManager.GetString("HEIGHTCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG品質率.
        /// </summary>
        public static string JPEGQUALITY {
            get {
                return ResourceManager.GetString("JPEGQUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このファイル形式のサポートは限定的です。.
        /// </summary>
        public static string LIMITED {
            get {
                return ResourceManager.GetString("LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上記のリスト内のすべてのスキャンされたドキュメントが削除されます。続行しますか？.
        /// </summary>
        public static string LISTREMOVEWARN {
            get {
                return ResourceManager.GetString("LISTREMOVEWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロード.
        /// </summary>
        public static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to まとめて.
        /// </summary>
        public static string MERGE {
            get {
                return ResourceManager.GetString("MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDFをマージ.
        /// </summary>
        public static string MERGEPDF {
            get {
                return ResourceManager.GetString("MERGEPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マークされた
        ///PDFをマージ.
        /// </summary>
        public static string MERGESELECTED {
            get {
                return ResourceManager.GetString("MERGESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [分].
        /// </summary>
        public static string MINUTE {
            get {
                return ResourceManager.GetString("MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [月].
        /// </summary>
        public static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アクションなし.
        /// </summary>
        public static string NO_ACTION {
            get {
                return ResourceManager.GetString("NO ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to どれでもない.
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パッチ コードが検出されませんでした.
        /// </summary>
        public static string NOPATCHCODE {
            get {
                return ResourceManager.GetString("NOPATCHCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロファイルが選択されていません.
        /// </summary>
        public static string NOPROFILE {
            get {
                return ResourceManager.GetString("NOPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR.
        /// </summary>
        public static string OCR {
            get {
                return ResourceManager.GetString("OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR PDFを保存.
        /// </summary>
        public static string OCRPDFSAVE {
            get {
                return ResourceManager.GetString("OCRPDFSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Ocr プロセスに余分な時間がかかります。.
        /// </summary>
        public static string OCRTIME {
            get {
                return ResourceManager.GetString("OCRTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私の他のアプリ.
        /// </summary>
        public static string OTHERAPPS {
            get {
                return ResourceManager.GetString("OTHERAPPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他の設定.
        /// </summary>
        public static string OTHERSETTINGS {
            get {
                return ResourceManager.GetString("OTHERSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to また、必要に応じてtesseract -ocrからtesseract 4.1.0用の他の言語データファイルをダウンロードします。それをTessdataフォルダに入れてください.
        /// </summary>
        public static string OTHERTESSERACT {
            get {
                return ResourceManager.GetString("OTHERTESSERACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他のtesseract言語データ.
        /// </summary>
        public static string OTHERTESSERACTLINK {
            get {
                return ResourceManager.GetString("OTHERTESSERACTLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スキャン文書の圧縮ファイルを直接上書き.
        /// </summary>
        public static string OVERWRITECOMPRESSED {
            get {
                return ResourceManager.GetString("OVERWRITECOMPRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページ番号.
        /// </summary>
        public static string PAGENUMBER {
            get {
                return ResourceManager.GetString("PAGENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDFファイルを直接開く.
        /// </summary>
        public static string PDFOPEN {
            get {
                return ResourceManager.GetString("PDFOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDFを保存.
        /// </summary>
        public static string PDFPROTECT {
            get {
                return ResourceManager.GetString("PDFPROTECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF フォルダの変更を見る.
        /// </summary>
        public static string PDFTRACK {
            get {
                return ResourceManager.GetString("PDFTRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ここで行われた設定は、すべてのPDFレコードに影響します。
        ///また、PDF保護はサードパーティアプリケーションによって破られる可能性があります。.
        /// </summary>
        public static string PDFWARN {
            get {
                return ResourceManager.GetString("PDFWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル
        ///プレビュー.
        /// </summary>
        public static string PREVIEWFILE {
            get {
                return ResourceManager.GetString("PREVIEWFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像プレビューサイズ.
        /// </summary>
        public static string PREVIEWSIZE {
            get {
                return ResourceManager.GetString("PREVIEWSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR検出.
        /// </summary>
        public static string QRDETECT {
            get {
                return ResourceManager.GetString("QRDETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アクティブなページ
        ///を読む.
        /// </summary>
        public static string READACTIVEPAGE {
            get {
                return ResourceManager.GetString("READACTIVEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザメニューに追加.
        /// </summary>
        public static string REGSTI {
            get {
                return ResourceManager.GetString("REGSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドキュメント一覧から処理済みファイルを削除.
        /// </summary>
        public static string REMOVEPROCESSEDIMAGE {
            get {
                return ResourceManager.GetString("REMOVEPROCESSEDIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択した画像を削除しますか?.
        /// </summary>
        public static string REMOVESELECTED {
            get {
                return ResourceManager.GetString("REMOVESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページを入れ替える.
        /// </summary>
        public static string REPLACEPAGE {
            get {
                return ResourceManager.GetString("REPLACEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解像度.
        /// </summary>
        public static string RES {
            get {
                return ResourceManager.GetString("RES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リセット.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アプリケーションを再起動する必要があります。.
        /// </summary>
        public static string RESTARTAPP {
            get {
                return ResourceManager.GetString("RESTARTAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パソコンを再起動.
        /// </summary>
        public static string RESTARTCOMP {
            get {
                return ResourceManager.GetString("RESTARTCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リバース.
        /// </summary>
        public static string REVERSE {
            get {
                return ResourceManager.GetString("REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180 度回転.
        /// </summary>
        public static string Rotate180 {
            get {
                return ResourceManager.GetString("Rotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 270 度回転.
        /// </summary>
        public static string Rotate270 {
            get {
                return ResourceManager.GetString("Rotate270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90度回転.
        /// </summary>
        public static string Rotate90 {
            get {
                return ResourceManager.GetString("Rotate90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回転を適用して保存しますか？.
        /// </summary>
        public static string ROTSAVE {
            get {
                return ResourceManager.GetString("ROTSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDFを保存.
        /// </summary>
        public static string SAVEPDF {
            get {
                return ResourceManager.GetString("SAVEPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロフィールを隠す.
        /// </summary>
        public static string SAVEPROFILE {
            get {
                return ResourceManager.GetString("SAVEPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to おすすめを保存.
        /// </summary>
        public static string SAVESELECTED {
            get {
                return ResourceManager.GetString("SAVESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タラ.
        /// </summary>
        public static string SCAN {
            get {
                return ResourceManager.GetString("SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スキャナー.
        /// </summary>
        public static string SCANNER {
            get {
                return ResourceManager.GetString("SCANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2番].
        /// </summary>
        public static string SECOND {
            get {
                return ResourceManager.GetString("SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 少なくとも2つのPDF
        ///ファイルを選択してください.
        /// </summary>
        public static string SELECTTWOPDF {
            get {
                return ResourceManager.GetString("SELECTTWOPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 各ページを個別にスキャン.
        /// </summary>
        public static string SEPERATESCAN {
            get {
                return ResourceManager.GetString("SEPERATESCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 各ページを別々のファイルに保存するファイルは、以下に指定されたフォルダに保存されます。.
        /// </summary>
        public static string SEPERATESCANTOOLTIP {
            get {
                return ResourceManager.GetString("SEPERATESCANTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラケット.
        /// </summary>
        public static string SEPERATOR {
            get {
                return ResourceManager.GetString("SEPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 調整.
        /// </summary>
        public static string SETTİNGS {
            get {
                return ResourceManager.GetString("SETTİNGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クイックスキャン後にファイルを表示.
        /// </summary>
        public static string SHOWFILE {
            get {
                return ResourceManager.GetString("SHOWFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダに表示.
        /// </summary>
        public static string SHOWFOLDER {
            get {
                return ResourceManager.GetString("SHOWFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 比率を教えてください.
        /// </summary>
        public static string SHOWPROGRESS {
            get {
                return ResourceManager.GetString("SHOWPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 叩き潰せ.
        /// </summary>
        public static string SLICE {
            get {
                return ResourceManager.GetString("SLICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソース言語.
        /// </summary>
        public static string SOURCELANG {
            get {
                return ResourceManager.GetString("SOURCELANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 壊れた.
        /// </summary>
        public static string SPLIT {
            get {
                return ResourceManager.GetString("SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダブルクリックで復元、右クリックで展開.
        /// </summary>
        public static string SPLITTERTOOLTIP {
            get {
                return ResourceManager.GetString("SPLITTERTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソースを選択.
        /// </summary>
        public static string SRC {
            get {
                return ResourceManager.GetString("SRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソースカラー.
        /// </summary>
        public static string SRCCOLOR {
            get {
                return ResourceManager.GetString("SRCCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右クリックして色を選択.
        /// </summary>
        public static string SRCCOLORTIP {
            get {
                return ResourceManager.GetString("SRCCOLORTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 始める.
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チケット.
        /// </summary>
        public static string TAG {
            get {
                return ResourceManager.GetString("TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一部のタスクが実行中です。終了するまで待ちます。.
        /// </summary>
        public static string TASKSRUNNING {
            get {
                return ResourceManager.GetString("TASKSRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テッセラクト.
        /// </summary>
        public static string TESSERACT {
            get {
                return ResourceManager.GetString("TESSERACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesseract 言語を選択.
        /// </summary>
        public static string TESSLANGSELECT {
            get {
                return ResourceManager.GetString("TESSLANGSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メティン.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字角度.
        /// </summary>
        public static string TEXTANGLE {
            get {
                return ResourceManager.GetString("TEXTANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字サイズ.
        /// </summary>
        public static string TEXTSIZE {
            get {
                return ResourceManager.GetString("TEXTSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アプリケーションで使用されるサードパーティ ライブラリ.
        /// </summary>
        public static string THIRDPARTY {
            get {
                return ResourceManager.GetString("THIRDPARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to しきい値.
        /// </summary>
        public static string THRESHOLD {
            get {
                return ResourceManager.GetString("THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [時間].
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翻訳.
        /// </summary>
        public static string TRANSLATE {
            get {
                return ResourceManager.GetString("TRANSLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロセスは進行中です。完了するまで待ちます。.
        /// </summary>
        public static string TRANSLATEPENDING {
            get {
                return ResourceManager.GetString("TRANSLATEPENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 絵をトリミング.
        /// </summary>
        public static string TRIMIMAGE {
            get {
                return ResourceManager.GetString("TRIMIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双方向.
        /// </summary>
        public static string TWOSIDE {
            get {
                return ResourceManager.GetString("TWOSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザメニューから削除.
        /// </summary>
        public static string UNREGSTI {
            get {
                return ResourceManager.GetString("UNREGSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデート.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ユーザー名].
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2019 x 86およびx 64ランタイム.
        /// </summary>
        public static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて見る.
        /// </summary>
        public static string VIEWALL {
            get {
                return ResourceManager.GetString("VIEWALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シャットダウンまたは再起動セット!!.
        /// </summary>
        public static string WARNREBOOT {
            get {
                return ResourceManager.GetString("WARNREBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 透かし.
        /// </summary>
        public static string WATERMARK {
            get {
                return ResourceManager.GetString("WATERMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最多の数.
        /// </summary>
        public static string WIDTHCOUNT {
            get {
                return ResourceManager.GetString("WIDTHCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [年].
        /// </summary>
        public static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
    }
}
