//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwainControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_tr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwainControl.Properties.Resources.tr", typeof(Resources_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKINDA.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOSYAYA
        ///BELGE EKLE.
        /// </summary>
        public static string ADDDOC {
            get {
                return ResourceManager.GetString("ADDDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR VERİSİNİ KAYDET.
        /// </summary>
        public static string ADDOCRTODB {
            get {
                return ResourceManager.GetString("ADDOCRTODB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu İşaretliyse Aşağıda İşaretli Evraka Soldaki Aktif Evrakın İçerdiği Metin İçerik Olarak Veritabanına Kaydedilir..
        /// </summary>
        public static string ADDOCRTOOLTIP {
            get {
                return ResourceManager.GetString("ADDOCRTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOKÜMAN
        ///BESLEYİCİ.
        /// </summary>
        public static string ADF {
            get {
                return ResourceManager.GetString("ADF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜMÜ.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İÇERİK KOPYALAMAYA İZİN VER.
        /// </summary>
        public static string ALLOWCOPY {
            get {
                return ResourceManager.GetString("ALLOWCOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELGE DÜZENLEMEYE İZİN VER.
        /// </summary>
        public static string ALLOWEDIT {
            get {
                return ResourceManager.GetString("ALLOWEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAZDIRMAYA İZİN VER.
        /// </summary>
        public static string ALLOWPRINT {
            get {
                return ResourceManager.GetString("ALLOWPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu uygulama tarama ve belge takibini kolaylaştırmak amacıyla geliştirilmiştir..
        /// </summary>
        public static string APPDESC {
            get {
                return ResourceManager.GetString("APPDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UYGULA.
        /// </summary>
        public static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENK UYGULA.
        /// </summary>
        public static string APPLYCOLOR {
            get {
                return ResourceManager.GetString("APPLYCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Zaten Çalışıyor..
        /// </summary>
        public static string APPRUNNING {
            get {
                return ResourceManager.GetString("APPRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTOMATİK.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik Kayıt Klasörünü Belirtin..
        /// </summary>
        public static string AUTOFOLDER {
            get {
                return ResourceManager.GetString("AUTOFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik Kayıt Yolu Değişti. Eski Dosyalar Yeni Belirlenen Klasöre Taşınmayacaktır..
        /// </summary>
        public static string AUTOFOLDERCHANGE {
            get {
                return ResourceManager.GetString("AUTOFOLDERCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTOMATİK
        ///KAYIT.
        /// </summary>
        public static string AUTOPATH {
            get {
                return ResourceManager.GetString("AUTOPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTOMATİK RESİM.
        /// </summary>
        public static string AutoPicture {
            get {
                return ResourceManager.GetString("AutoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTOMATİK DÖNDÜR.
        /// </summary>
        public static string AUTOROTATE {
            get {
                return ResourceManager.GetString("AUTOROTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTOMATİK METİN.
        /// </summary>
        public static string AutoText {
            get {
                return ResourceManager.GetString("AutoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOPLU İŞ.
        /// </summary>
        public static string BATCH {
            get {
                return ResourceManager.GetString("BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aşağıda Belirtilen Klasöre Resim Dosyaları Eklendiğinde Program Açık Olduğu Müddetçe Aynı Klasörde Pdf Dosyasına Otomatik Çevirme İşlemi Yapılır.
        /// </summary>
        public static string BATCHDESC {
            get {
                return ResourceManager.GetString("BATCHDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTOMATİK KENAR TESPİTİ.
        /// </summary>
        public static string BORDERDETECT {
            get {
                return ResourceManager.GetString("BORDERDETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİYAH BEYAZ.
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAKVİM.
        /// </summary>
        public static string CALENDAR {
            get {
                return ResourceManager.GetString("CALENDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAMERA.
        /// </summary>
        public static string CAMERA {
            get {
                return ResourceManager.GetString("CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LİSTEYİ TEMİZLE.
        /// </summary>
        public static string CLEARLIST {
            get {
                return ResourceManager.GetString("CLEARLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİLGİSAYARI KAPAT.
        /// </summary>
        public static string CLOSECOMP {
            get {
                return ResourceManager.GetString("CLOSECOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENKLİ.
        /// </summary>
        public static string COLOR {
            get {
                return ResourceManager.GetString("COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşik Değeri Ayarladıktan Sonra Buna Tıklarsanız İkinci Bir Renk Seçimi Yapabilirsiniz..
        /// </summary>
        public static string COLORCHANGETIP {
            get {
                return ResourceManager.GetString("COLORCHANGETIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIKIŞTIR.
        /// </summary>
        public static string COMPRESS {
            get {
                return ResourceManager.GetString("COMPRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKUNAN İÇERİK.
        /// </summary>
        public static string CONTENT {
            get {
                return ResourceManager.GetString("CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesseract ve leptonica ikili dosyaları Visual Studio 2019 ile derlendiğinden, Visual Studio 2019 Runtime&apos;ın kurulu olduğundan emin olmanız gerekir.
        ///.
        /// </summary>
        public static string CRUNTIME {
            get {
                return ResourceManager.GetString("CRUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GÜN].
        /// </summary>
        public static string DAY {
            get {
                return ResourceManager.GetString("DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARSAYILAN.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarama.
        /// </summary>
        public static string DEFAULTSCANNAME {
            get {
                return ResourceManager.GetString("DEFAULTSCANNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİL.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EĞRİLİK DÜZELT.
        /// </summary>
        public static string DESKEW {
            get {
                return ResourceManager.GetString("DESKEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEDEF DİL.
        /// </summary>
        public static string DESTLANG {
            get {
                return ResourceManager.GetString("DESTLANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVRAK.
        /// </summary>
        public static string DOCUMENT {
            get {
                return ResourceManager.GetString("DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METİN ÇİZ.
        /// </summary>
        public static string DRAWTEXT {
            get {
                return ResourceManager.GetString("DRAWTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEDEF RENK.
        /// </summary>
        public static string DSTCOLOR {
            get {
                return ResourceManager.GetString("DSTCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOŞ SAYFALARI GEÇ.
        /// </summary>
        public static string EMPTYPAGE {
            get {
                return ResourceManager.GetString("EMPTYPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞİFRELE.
        /// </summary>
        public static string ENCRYPT {
            get {
                return ResourceManager.GetString("ENCRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyp Dosyalarını Direkt Aç.
        /// </summary>
        public static string EYPOPEN {
            get {
                return ResourceManager.GetString("EYPOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIZLI
        ///TARA.
        /// </summary>
        public static string FASTSCAN {
            get {
                return ResourceManager.GetString("FASTSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı Tarama Bitince Yapılacak İşlem.
        /// </summary>
        public static string FASTSCANAFTER {
            get {
                return ResourceManager.GetString("FASTSCANAFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOSYA.
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOSYA ADI:.
        /// </summary>
        public static string FILENAME {
            get {
                return ResourceManager.GetString("FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÜZ YATAKLI.
        /// </summary>
        public static string FLATBED {
            get {
                return ResourceManager.GetString("FLATBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAZI TİPİ.
        /// </summary>
        public static string FONT {
            get {
                return ResourceManager.GetString("FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAFİK.
        /// </summary>
        public static string GRAPH {
            get {
                return ResourceManager.GetString("GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRİ.
        /// </summary>
        public static string GRAY {
            get {
                return ResourceManager.GetString("GRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARAYÜZ GÖSTER.
        /// </summary>
        public static string GUI {
            get {
                return ResourceManager.GetString("GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GUID].
        /// </summary>
        public static string GUID {
            get {
                return ResourceManager.GetString("GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOY ADETİ.
        /// </summary>
        public static string HEIGHTCOUNT {
            get {
                return ResourceManager.GetString("HEIGHTCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG KALİTE ORANI.
        /// </summary>
        public static string JPEGQUALITY {
            get {
                return ResourceManager.GetString("JPEGQUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOL.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Dosya Formatının Kısıtlı Desteği Vardır..
        /// </summary>
        public static string LIMITED {
            get {
                return ResourceManager.GetString("LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üstteki Listede Bulunan Tüm Taranan Evrak Silinecek Devam Etmek İstiyor Musun?.
        /// </summary>
        public static string LISTREMOVEWARN {
            get {
                return ResourceManager.GetString("LISTREMOVEWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YÜKLE.
        /// </summary>
        public static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİRLEŞTİR.
        /// </summary>
        public static string MERGE {
            get {
                return ResourceManager.GetString("MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF BİRLEŞTİR.
        /// </summary>
        public static string MERGEPDF {
            get {
                return ResourceManager.GetString("MERGEPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İŞARETLİ PDFLERİ
        ///BİRLEŞTİR.
        /// </summary>
        public static string MERGESELECTED {
            get {
                return ResourceManager.GetString("MERGESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DAKİKA].
        /// </summary>
        public static string MINUTE {
            get {
                return ResourceManager.GetString("MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AY].
        /// </summary>
        public static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İŞLEM YOK.
        /// </summary>
        public static string NO_ACTION {
            get {
                return ResourceManager.GetString("NO ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HİÇBİRİ.
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yama Kodu Algılanmadı.
        /// </summary>
        public static string NOPATCHCODE {
            get {
                return ResourceManager.GetString("NOPATCHCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFİL SEÇİLMEDİ.
        /// </summary>
        public static string NOPROFILE {
            get {
                return ResourceManager.GetString("NOPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR YAP.
        /// </summary>
        public static string OCR {
            get {
                return ResourceManager.GetString("OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR PDF SAKLA.
        /// </summary>
        public static string OCRPDFSAVE {
            get {
                return ResourceManager.GetString("OCRPDFSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Ocr İşlemi Fazladan Zaman Alır..
        /// </summary>
        public static string OCRTIME {
            get {
                return ResourceManager.GetString("OCRTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DİĞER UYGULAMALARIM.
        /// </summary>
        public static string OTHERAPPS {
            get {
                return ResourceManager.GetString("OTHERAPPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DİĞER AYARLAR.
        /// </summary>
        public static string OTHERSETTINGS {
            get {
                return ResourceManager.GetString("OTHERSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayrıca tesseract 4.1.0 için diğer dil veri dosyalarını gerekirse tesseract-ocr&apos;den indirin. Tessdata klasörüne koyun..
        /// </summary>
        public static string OTHERTESSERACT {
            get {
                return ResourceManager.GetString("OTHERTESSERACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer tesseract dil verileri.
        /// </summary>
        public static string OTHERTESSERACTLINK {
            get {
                return ResourceManager.GetString("OTHERTESSERACTLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taranan Belgelerde Sıkıştırılan Dosyayı Direkt Üzerine Yaz.
        /// </summary>
        public static string OVERWRITECOMPRESSED {
            get {
                return ResourceManager.GetString("OVERWRITECOMPRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAYFA NO.
        /// </summary>
        public static string PAGENUMBER {
            get {
                return ResourceManager.GetString("PAGENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞİFRE.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Dosyalarını Direkt Aç.
        /// </summary>
        public static string PDFOPEN {
            get {
                return ResourceManager.GetString("PDFOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF KORU.
        /// </summary>
        public static string PDFPROTECT {
            get {
                return ResourceManager.GetString("PDFPROTECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF KLASÖR DEĞİŞİMİNİ İZLE.
        /// </summary>
        public static string PDFTRACK {
            get {
                return ResourceManager.GetString("PDFTRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BURDA YAPILAN AYARLAR TÜM PDF KAYITLARINI ETKİLER.
        ///AYRICA PDF KORUMASI 3.PARTİ UYGULAMALAR TARAFINDAN KIRILABİLİR..
        /// </summary>
        public static string PDFWARN {
            get {
                return ResourceManager.GetString("PDFWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOSYA
        ///ÖNİZLEME.
        /// </summary>
        public static string PREVIEWFILE {
            get {
                return ResourceManager.GetString("PREVIEWFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESİM ÖNİZLEME BOYUTU.
        /// </summary>
        public static string PREVIEWSIZE {
            get {
                return ResourceManager.GetString("PREVIEWSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR ALGILA.
        /// </summary>
        public static string QRDETECT {
            get {
                return ResourceManager.GetString("QRDETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKTİF SAYFAYI
        ///OKU.
        /// </summary>
        public static string READACTIVEPAGE {
            get {
                return ResourceManager.GetString("READACTIVEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARAYICI MENÜSÜNE
        ///EKLE.
        /// </summary>
        public static string REGSTI {
            get {
                return ResourceManager.GetString("REGSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlenen Dosyaları Belge Listesinden Sil.
        /// </summary>
        public static string REMOVEPROCESSEDIMAGE {
            get {
                return ResourceManager.GetString("REMOVEPROCESSEDIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili Resimi Silmek İstiyor musun?.
        /// </summary>
        public static string REMOVESELECTED {
            get {
                return ResourceManager.GetString("REMOVESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfaları Yer Değiştir.
        /// </summary>
        public static string REPLACEPAGE {
            get {
                return ResourceManager.GetString("REPLACEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇÖZÜNÜRLÜK.
        /// </summary>
        public static string RES {
            get {
                return ResourceManager.GetString("RES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIFIRLA.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamanın Yeniden Başlatılması Gerekir..
        /// </summary>
        public static string RESTARTAPP {
            get {
                return ResourceManager.GetString("RESTARTAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİLGİSAYARI YENİDEN BAŞLAT.
        /// </summary>
        public static string RESTARTCOMP {
            get {
                return ResourceManager.GetString("RESTARTCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERSİ.
        /// </summary>
        public static string REVERSE {
            get {
                return ResourceManager.GetString("REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAĞ.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180 DERECE DÖNDÜR.
        /// </summary>
        public static string Rotate180 {
            get {
                return ResourceManager.GetString("Rotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 270 DERECE DÖNDÜR.
        /// </summary>
        public static string Rotate270 {
            get {
                return ResourceManager.GetString("Rotate270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 DERECE DÖNDÜR.
        /// </summary>
        public static string Rotate90 {
            get {
                return ResourceManager.GetString("Rotate90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döndürme Uygulanarak Kaydedilsin mi?.
        /// </summary>
        public static string ROTSAVE {
            get {
                return ResourceManager.GetString("ROTSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF KAYDET.
        /// </summary>
        public static string SAVEPDF {
            get {
                return ResourceManager.GetString("SAVEPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFİL SAKLA.
        /// </summary>
        public static string SAVEPROFILE {
            get {
                return ResourceManager.GetString("SAVEPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEÇİLİLERİ KAYDET.
        /// </summary>
        public static string SAVESELECTED {
            get {
                return ResourceManager.GetString("SAVESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARA.
        /// </summary>
        public static string SCAN {
            get {
                return ResourceManager.GetString("SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARAYICI.
        /// </summary>
        public static string SCANNER {
            get {
                return ResourceManager.GetString("SCANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SANİYE].
        /// </summary>
        public static string SECOND {
            get {
                return ResourceManager.GetString("SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN AZ İKİ PDF
        ///DOSYASI SEÇİN.
        /// </summary>
        public static string SELECTTWOPDF {
            get {
                return ResourceManager.GetString("SELECTTWOPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HER SAYFAYI AYRI TARA.
        /// </summary>
        public static string SEPERATESCAN {
            get {
                return ResourceManager.GetString("SEPERATESCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her Sayfayı Ayrı Dosyaya Kaydet Dosyalar Aşağıda Belirtilen Klasöre Kaydedilir..
        /// </summary>
        public static string SEPERATESCANTOOLTIP {
            get {
                return ResourceManager.GetString("SEPERATESCANTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYRAÇ.
        /// </summary>
        public static string SEPERATOR {
            get {
                return ResourceManager.GetString("SEPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYARLAR.
        /// </summary>
        public static string SETTİNGS {
            get {
                return ResourceManager.GetString("SETTİNGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIZLI TARAMA SONRASI DOSYAYI GÖSTER.
        /// </summary>
        public static string SHOWFILE {
            get {
                return ResourceManager.GetString("SHOWFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLASÖRDE GÖSTER.
        /// </summary>
        public static string SHOWFOLDER {
            get {
                return ResourceManager.GetString("SHOWFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YÜZDE GÖSTER.
        /// </summary>
        public static string SHOWPROGRESS {
            get {
                return ResourceManager.GetString("SHOWPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARÇALA.
        /// </summary>
        public static string SLICE {
            get {
                return ResourceManager.GetString("SLICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAYNAK DİL.
        /// </summary>
        public static string SOURCELANG {
            get {
                return ResourceManager.GetString("SOURCELANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parçalanmış.
        /// </summary>
        public static string SPLIT {
            get {
                return ResourceManager.GetString("SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Yüklemek İçin Çift Tıklayın, Genişletmek İçin Sağ Tıklayın.
        /// </summary>
        public static string SPLITTERTOOLTIP {
            get {
                return ResourceManager.GetString("SPLITTERTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAYNAK SEÇ.
        /// </summary>
        public static string SRC {
            get {
                return ResourceManager.GetString("SRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAYNAK RENK.
        /// </summary>
        public static string SRCCOLOR {
            get {
                return ResourceManager.GetString("SRCCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sağ Tıklayıp Renk Seçimi Yapın.
        /// </summary>
        public static string SRCCOLORTIP {
            get {
                return ResourceManager.GetString("SRCCOLORTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAŞLAT.
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETİKET.
        /// </summary>
        public static string TAG {
            get {
                return ResourceManager.GetString("TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bazı Görevler Çalışıyor Bitmesini Bekleyin..
        /// </summary>
        public static string TASKSRUNNING {
            get {
                return ResourceManager.GetString("TASKSRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESSERACT.
        /// </summary>
        public static string TESSERACT {
            get {
                return ResourceManager.GetString("TESSERACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesseract Dilini Seçin.
        /// </summary>
        public static string TESSLANGSELECT {
            get {
                return ResourceManager.GetString("TESSLANGSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METİN.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METİN AÇI.
        /// </summary>
        public static string TEXTANGLE {
            get {
                return ResourceManager.GetString("TEXTANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METİN BOYUT.
        /// </summary>
        public static string TEXTSIZE {
            get {
                return ResourceManager.GetString("TEXTSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UYGULAMADA KULLANILAN 3.PARTİ KÜTÜPHANELER.
        /// </summary>
        public static string THIRDPARTY {
            get {
                return ResourceManager.GetString("THIRDPARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EŞİK.
        /// </summary>
        public static string THRESHOLD {
            get {
                return ResourceManager.GetString("THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SAAT].
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇEVİRİ.
        /// </summary>
        public static string TRANSLATE {
            get {
                return ResourceManager.GetString("TRANSLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Devam Ediyor. Bitmesini Bekleyin..
        /// </summary>
        public static string TRANSLATEPENDING {
            get {
                return ResourceManager.GetString("TRANSLATEPENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESMİ KIRP.
        /// </summary>
        public static string TRIMIMAGE {
            get {
                return ResourceManager.GetString("TRIMIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İKİ YÖNLÜ.
        /// </summary>
        public static string TWOSIDE {
            get {
                return ResourceManager.GetString("TWOSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARAYICI MENÜSÜNDEN
        ///KALDIR.
        /// </summary>
        public static string UNREGSTI {
            get {
                return ResourceManager.GetString("UNREGSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÜNCELLE.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KULLANICIADI].
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2019 x86 ve x64 Çalışma Zamanları.
        /// </summary>
        public static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜMÜNÜ
        ///GÖR.
        /// </summary>
        public static string VIEWALL {
            get {
                return ResourceManager.GetString("VIEWALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapatma Veya Yeniden Başlatma Ayarlanmış..
        /// </summary>
        public static string WARNREBOOT {
            get {
                return ResourceManager.GetString("WARNREBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FİLİGRAN.
        /// </summary>
        public static string WATERMARK {
            get {
                return ResourceManager.GetString("WATERMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN ADETİ.
        /// </summary>
        public static string WIDTHCOUNT {
            get {
                return ResourceManager.GetString("WIDTHCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [YIL].
        /// </summary>
        public static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
    }
}
