//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwainControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwainControl.Properties.Resources.es", typeof(Resources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACERCA DE.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÑADIR DOCUMENTO
        ///AL ARCHIVO.
        /// </summary>
        public static string ADDDOC {
            get {
                return ResourceManager.GetString("ADDDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÑADIR OCR A LA BASE DE DATOS.
        /// </summary>
        public static string ADDOCRTODB {
            get {
                return ResourceManager.GetString("ADDOCRTODB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si esto está marcado, el documento marcado a continuación se guarda en la base de datos como el texto del documento activo a la izquierda..
        /// </summary>
        public static string ADDOCRTOOLTIP {
            get {
                return ResourceManager.GetString("ADDOCRTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimentador automático de documentos (ADF).
        /// </summary>
        public static string ADF {
            get {
                return ResourceManager.GetString("ADF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMITIR COPIA.
        /// </summary>
        public static string ALLOWCOPY {
            get {
                return ResourceManager.GetString("ALLOWCOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir edición.
        /// </summary>
        public static string ALLOWEDIT {
            get {
                return ResourceManager.GetString("ALLOWEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMITIR IMPRESIÓN.
        /// </summary>
        public static string ALLOWPRINT {
            get {
                return ResourceManager.GetString("ALLOWPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta aplicación ha sido desarrollada para facilitar el escaneo y el seguimiento de documentos..
        /// </summary>
        public static string APPDESC {
            get {
                return ResourceManager.GetString("APPDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APLICAR.
        /// </summary>
        public static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar el color.
        /// </summary>
        public static string APPLYCOLOR {
            get {
                return ResourceManager.GetString("APPLYCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La aplicación ya se está ejecutando.
        /// </summary>
        public static string APPRUNNING {
            get {
                return ResourceManager.GetString("APPRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMÁTICO.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecer carpeta de guardado automático.
        /// </summary>
        public static string AUTOFOLDER {
            get {
                return ResourceManager.GetString("AUTOFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cambiado la ruta de guardado automático. Los archivos antiguos no se moverán a la carpeta recién determinada..
        /// </summary>
        public static string AUTOFOLDERCHANGE {
            get {
                return ResourceManager.GetString("AUTOFOLDERCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escaneo automático.
        /// </summary>
        public static string AUTOPATH {
            get {
                return ResourceManager.GetString("AUTOPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGEN AUTOMÁTICA.
        /// </summary>
        public static string AutoPicture {
            get {
                return ResourceManager.GetString("AutoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproducción automática.
        /// </summary>
        public static string AUTOROTATE {
            get {
                return ResourceManager.GetString("AUTOROTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXTO AUTOMÁTICO.
        /// </summary>
        public static string AutoText {
            get {
                return ResourceManager.GetString("AutoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATCH.
        /// </summary>
        public static string BATCH {
            get {
                return ResourceManager.GetString("BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuando se agregan archivos de imagen a la carpeta especificada a continuación, la conversión automática a archivos PDF en la misma carpeta se realiza siempre que el programa esté abierto..
        /// </summary>
        public static string BATCHDESC {
            get {
                return ResourceManager.GetString("BATCHDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETECCIÓN AUTOMÁTICA DE BORDES.
        /// </summary>
        public static string BORDERDETECT {
            get {
                return ResourceManager.GetString("BORDERDETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEGRO/BLANCO.
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALENDARIO.
        /// </summary>
        public static string CALENDAR {
            get {
                return ResourceManager.GetString("CALENDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁMARA.
        /// </summary>
        public static string CAMERA {
            get {
                return ResourceManager.GetString("CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string CLEARLIST {
            get {
                return ResourceManager.GetString("CLEARLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIERRE EL ORDENADOR.
        /// </summary>
        public static string CLOSECOMP {
            get {
                return ResourceManager.GetString("CLOSECOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLOR.
        /// </summary>
        public static string COLOR {
            get {
                return ResourceManager.GetString("COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si hace clic en esto después de establecer el valor umbral, puede hacer una segunda selección de color..
        /// </summary>
        public static string COLORCHANGETIP {
            get {
                return ResourceManager.GetString("COLORCHANGETIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprimir.
        /// </summary>
        public static string COMPRESS {
            get {
                return ResourceManager.GetString("COMPRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTENIDO.
        /// </summary>
        public static string CONTENT {
            get {
                return ResourceManager.GetString("CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dado que los binarios tesseract y leptonica se compilan con Visual Studio 2019, ¡debe asegurarse de tener instalado Visual Studio 2019 Runtime.
        /// </summary>
        public static string CRUNTIME {
            get {
                return ResourceManager.GetString("CRUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Día].
        /// </summary>
        public static string DAY {
            get {
                return ResourceManager.GetString("DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POR DEFECTO.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escanear.
        /// </summary>
        public static string DEFAULTSCANNAME {
            get {
                return ResourceManager.GetString("DEFAULTSCANNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESKEW.
        /// </summary>
        public static string DESKEW {
            get {
                return ResourceManager.GetString("DESKEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idioma de destino.
        /// </summary>
        public static string DESTLANG {
            get {
                return ResourceManager.GetString("DESTLANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENTAR.
        /// </summary>
        public static string DOCUMENT {
            get {
                return ResourceManager.GetString("DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herramienta Inserción de texto.
        /// </summary>
        public static string DRAWTEXT {
            get {
                return ResourceManager.GetString("DRAWTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color de destino.
        /// </summary>
        public static string DSTCOLOR {
            get {
                return ResourceManager.GetString("DSTCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagina vacia.
        /// </summary>
        public static string EMPTYPAGE {
            get {
                return ResourceManager.GetString("EMPTYPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÍFRALO.
        /// </summary>
        public static string ENCRYPT {
            get {
                return ResourceManager.GetString("ENCRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abra los archivos Eyp directamente.
        /// </summary>
        public static string EYPOPEN {
            get {
                return ResourceManager.GetString("EYPOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco FAST.
        /// </summary>
        public static string FASTSCAN {
            get {
                return ResourceManager.GetString("FASTSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Después del trabajo de escaneo rápido.
        /// </summary>
        public static string FASTSCANAFTER {
            get {
                return ResourceManager.GetString("FASTSCANAFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARCHIVO.
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de archivo.
        /// </summary>
        public static string FILENAME {
            get {
                return ResourceManager.GetString("FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FIX {
            get {
                return ResourceManager.GetString("FIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES Flatbed.
        /// </summary>
        public static string FLATBED {
            get {
                return ResourceManager.GetString("FLATBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuente.
        /// </summary>
        public static string FONT {
            get {
                return ResourceManager.GetString("FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gráfico.
        /// </summary>
        public static string GRAPH {
            get {
                return ResourceManager.GetString("GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gris.
        /// </summary>
        public static string GRAY {
            get {
                return ResourceManager.GetString("GRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOSTRAR INTERFAZ.
        /// </summary>
        public static string GUI {
            get {
                return ResourceManager.GetString("GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GUID].
        /// </summary>
        public static string GUID {
            get {
                return ResourceManager.GetString("GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUENTA LA ALTURA.
        /// </summary>
        public static string HEIGHTCOUNT {
            get {
                return ResourceManager.GetString("HEIGHTCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calidad JPEG.
        /// </summary>
        public static string JPEGQUALITY {
            get {
                return ResourceManager.GetString("JPEGQUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IZQUIERDA.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este formato de archivo tiene soporte limitado..
        /// </summary>
        public static string LIMITED {
            get {
                return ResourceManager.GetString("LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los documentos escaneados en la lista superior se eliminarán. ¿Desea continuar?.
        /// </summary>
        public static string LISTREMOVEWARN {
            get {
                return ResourceManager.GetString("LISTREMOVEWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARGA.
        /// </summary>
        public static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combinar.
        /// </summary>
        public static string MERGE {
            get {
                return ResourceManager.GetString("MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unir un PDF.
        /// </summary>
        public static string MERGEPDF {
            get {
                return ResourceManager.GetString("MERGEPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMBINE EL PDF SELECCIONADO.
        /// </summary>
        public static string MERGESELECTED {
            get {
                return ResourceManager.GetString("MERGESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Minuto].
        /// </summary>
        public static string MINUTE {
            get {
                return ResourceManager.GetString("MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Mes].
        /// </summary>
        public static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin acción.
        /// </summary>
        public static string NO_ACTION {
            get {
                return ResourceManager.GetString("NO ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NINGUNO.
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha detectado ningún código de parche.
        /// </summary>
        public static string NOPATCHCODE {
            get {
                return ResourceManager.GetString("NOPATCHCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay perfil seleccionado..
        /// </summary>
        public static string NOPROFILE {
            get {
                return ResourceManager.GetString("NOPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR.
        /// </summary>
        public static string OCR {
            get {
                return ResourceManager.GetString("OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUARDAR OCR PDF.
        /// </summary>
        public static string OCRPDFSAVE {
            get {
                return ResourceManager.GetString("OCRPDFSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso Ocr en PDF requiere tiempo adicional..
        /// </summary>
        public static string OCRTIME {
            get {
                return ResourceManager.GetString("OCRTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otras aplicaciones.
        /// </summary>
        public static string OTHERAPPS {
            get {
                return ResourceManager.GetString("OTHERAPPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros ajustes.
        /// </summary>
        public static string OTHERSETTINGS {
            get {
                return ResourceManager.GetString("OTHERSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to También descargue otros archivos de datos de idioma para tesseract 4.1.0 de tesseract-ocr si es necesario. Ponlo en la carpeta tessdata..
        /// </summary>
        public static string OTHERTESSERACT {
            get {
                return ResourceManager.GetString("OTHERTESSERACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros datos de lenguaje tesseract.
        /// </summary>
        public static string OTHERTESSERACTLINK {
            get {
                return ResourceManager.GetString("OTHERTESSERACTLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrescriba directamente el archivo comprimido en los documentos escaneados.
        /// </summary>
        public static string OVERWRITECOMPRESSED {
            get {
                return ResourceManager.GetString("OVERWRITECOMPRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÚMERO DE PÁGINA.
        /// </summary>
        public static string PAGENUMBER {
            get {
                return ResourceManager.GetString("PAGENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRASEÑA.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir archivos pdf directamente.
        /// </summary>
        public static string PDFOPEN {
            get {
                return ResourceManager.GetString("PDFOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF ¡PROTEGE.
        /// </summary>
        public static string PDFPROTECT {
            get {
                return ResourceManager.GetString("PDFPROTECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VER EL CAMBIO DE CARPETA PDF.
        /// </summary>
        public static string PDFTRACK {
            get {
                return ResourceManager.GetString("PDFTRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LA CONFIGURACIÓN REALIZADA AQUÍ AFECTA A TODAS LAS GRABACIONES EN PDF. 
        ///TAMBIÉN LA PROTECCIÓN PDF PUEDE ser ROTA por APLICACIONES DE TERCEROS..
        /// </summary>
        public static string PDFWARN {
            get {
                return ResourceManager.GetString("PDFWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsualizar archivo.
        /// </summary>
        public static string PREVIEWFILE {
            get {
                return ResourceManager.GetString("PREVIEWFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista previa de la imagen.
        /// </summary>
        public static string PREVIEWSIZE {
            get {
                return ResourceManager.GetString("PREVIEWSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETECTE QR.
        /// </summary>
        public static string QRDETECT {
            get {
                return ResourceManager.GetString("QRDETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página activa.
        /// </summary>
        public static string READACTIVEPAGE {
            get {
                return ResourceManager.GetString("READACTIVEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRAR DISPOSITIVO STI.
        /// </summary>
        public static string REGSTI {
            get {
                return ResourceManager.GetString("REGSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar archivos procesados de la lista de documentos.
        /// </summary>
        public static string REMOVEPROCESSEDIMAGE {
            get {
                return ResourceManager.GetString("REMOVEPROCESSEDIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea eliminar el cuestionario seleccionado?.
        /// </summary>
        public static string REMOVESELECTED {
            get {
                return ResourceManager.GetString("REMOVESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reemplazar páginas.
        /// </summary>
        public static string REPLACEPAGE {
            get {
                return ResourceManager.GetString("REPLACEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOLUCIÓN.
        /// </summary>
        public static string RES {
            get {
                return ResourceManager.GetString("RES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña restaurada.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTARTAPP.
        /// </summary>
        public static string RESTARTAPP {
            get {
                return ResourceManager.GetString("RESTARTAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar el equipo.
        /// </summary>
        public static string RESTARTCOMP {
            get {
                return ResourceManager.GetString("RESTARTCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVERSO.
        /// </summary>
        public static string REVERSE {
            get {
                return ResourceManager.GetString("REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exacto.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotar 180 grados.
        /// </summary>
        public static string Rotate180 {
            get {
                return ResourceManager.GetString("Rotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotar 270 grados.
        /// </summary>
        public static string Rotate270 {
            get {
                return ResourceManager.GetString("Rotate270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotar 90 grados.
        /// </summary>
        public static string Rotate90 {
            get {
                return ResourceManager.GetString("Rotate90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar rotación.
        /// </summary>
        public static string ROTSAVE {
            get {
                return ResourceManager.GetString("ROTSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar PDF.
        /// </summary>
        public static string SAVEPDF {
            get {
                return ResourceManager.GetString("SAVEPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar perfil.
        /// </summary>
        public static string SAVEPROFILE {
            get {
                return ResourceManager.GetString("SAVEPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar selección.
        /// </summary>
        public static string SAVESELECTED {
            get {
                return ResourceManager.GetString("SAVESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESCANEO.
        /// </summary>
        public static string SCAN {
            get {
                return ResourceManager.GetString("SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCANNER.
        /// </summary>
        public static string SCANNER {
            get {
                return ResourceManager.GetString("SCANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Secundario].
        /// </summary>
        public static string SECOND {
            get {
                return ResourceManager.GetString("SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONE AL MENOS DOS ARCHIVOS PDF.
        /// </summary>
        public static string SELECTTWOPDF {
            get {
                return ResourceManager.GetString("SELECTTWOPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separado.
        /// </summary>
        public static string SEPERATESCAN {
            get {
                return ResourceManager.GetString("SEPERATESCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar cada página en archivos separados se guardan en la carpeta especificada a continuación..
        /// </summary>
        public static string SEPERATESCANTOOLTIP {
            get {
                return ResourceManager.GetString("SEPERATESCANTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separador.
        /// </summary>
        public static string SEPERATOR {
            get {
                return ResourceManager.GetString("SEPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURACIÓN.
        /// </summary>
        public static string SETTİNGS {
            get {
                return ResourceManager.GetString("SETTİNGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOSTRAR ARCHIVO DESPUÉS DE UN ESCANEO RÁPIDO.
        /// </summary>
        public static string SHOWFILE {
            get {
                return ResourceManager.GetString("SHOWFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar en la carpeta.
        /// </summary>
        public static string SHOWFOLDER {
            get {
                return ResourceManager.GetString("SHOWFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver el avance.
        /// </summary>
        public static string SHOWPROGRESS {
            get {
                return ResourceManager.GetString("SHOWPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORTAR.
        /// </summary>
        public static string SLICE {
            get {
                return ResourceManager.GetString("SLICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE LANGUAGE.
        /// </summary>
        public static string SOURCELANG {
            get {
                return ResourceManager.GetString("SOURCELANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraccionado.
        /// </summary>
        public static string SPLIT {
            get {
                return ResourceManager.GetString("SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga doble clic para restaurar, haga clic derecho para expandir.
        /// </summary>
        public static string SPLITTERTOOLTIP {
            get {
                return ResourceManager.GetString("SPLITTERTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar fuente.
        /// </summary>
        public static string SRC {
            get {
                return ResourceManager.GetString("SRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de colores de fuente.
        /// </summary>
        public static string SRCCOLOR {
            get {
                return ResourceManager.GetString("SRCCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga clic derecho para seleccionar el color de origen..
        /// </summary>
        public static string SRCCOLORTIP {
            get {
                return ResourceManager.GetString("SRCCOLORTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMENZAR.
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAG.
        /// </summary>
        public static string TAG {
            get {
                return ResourceManager.GetString("TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algunas tareas se ejecutan a la espera de que termine..
        /// </summary>
        public static string TASKSRUNNING {
            get {
                return ResourceManager.GetString("TASKSRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teseracto.
        /// </summary>
        public static string TESSERACT {
            get {
                return ResourceManager.GetString("TESSERACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Tesseract Language.
        /// </summary>
        public static string TESSLANGSELECT {
            get {
                return ResourceManager.GetString("TESSLANGSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXTO.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ángulo de texto.
        /// </summary>
        public static string TEXTANGLE {
            get {
                return ResourceManager.GetString("TEXTANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño del texto.
        /// </summary>
        public static string TEXTSIZE {
            get {
                return ResourceManager.GetString("TEXTSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIBLIOTECAS DE TERCEROS UTILIZADAS EN LA APLICACIÓN.
        /// </summary>
        public static string THIRDPARTY {
            get {
                return ResourceManager.GetString("THIRDPARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMBRAL.
        /// </summary>
        public static string THRESHOLD {
            get {
                return ResourceManager.GetString("THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HORA].
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSLATE.
        /// </summary>
        public static string TRANSLATE {
            get {
                return ResourceManager.GetString("TRANSLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso está en progreso. ¡Espera a que termine.
        /// </summary>
        public static string TRANSLATEPENDING {
            get {
                return ResourceManager.GetString("TRANSLATEPENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORTA LA IMAGEN.
        /// </summary>
        public static string TRIMIMAGE {
            get {
                return ResourceManager.GetString("TRIMIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOS LADOS.
        /// </summary>
        public static string TWOSIDE {
            get {
                return ResourceManager.GetString("TWOSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANULE EL REGISTRO DEL DISPOSITIVO STI.
        /// </summary>
        public static string UNREGSTI {
            get {
                return ResourceManager.GetString("UNREGSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTUALIZAR.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2019 x86 y x64 Runtimes.
        /// </summary>
        public static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VER TODOS.
        /// </summary>
        public static string VIEWALL {
            get {
                return ResourceManager.GetString("VIEWALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apagado o reinicio está establecido.
        /// </summary>
        public static string WARNREBOOT {
            get {
                return ResourceManager.GetString("WARNREBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCA DE AGUA.
        /// </summary>
        public static string WATERMARK {
            get {
                return ResourceManager.GetString("WATERMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECUENTO DE ANCHO.
        /// </summary>
        public static string WIDTHCOUNT {
            get {
                return ResourceManager.GetString("WIDTHCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Año].
        /// </summary>
        public static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
    }
}
