//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwainControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwainControl.Properties.Resources.en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD DOCUMENT
        ///TO FILE.
        /// </summary>
        public static string ADDDOC {
            get {
                return ResourceManager.GetString("ADDDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD OCR TO DATABASE.
        /// </summary>
        public static string ADDOCRTODB {
            get {
                return ResourceManager.GetString("ADDOCRTODB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is checked, the document marked below is saved in the database as the text of the active document on the left..
        /// </summary>
        public static string ADDOCRTOOLTIP {
            get {
                return ResourceManager.GetString("ADDOCRTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADF.
        /// </summary>
        public static string ADF {
            get {
                return ResourceManager.GetString("ADF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLOW COPY.
        /// </summary>
        public static string ALLOWCOPY {
            get {
                return ResourceManager.GetString("ALLOWCOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLOW EDIT.
        /// </summary>
        public static string ALLOWEDIT {
            get {
                return ResourceManager.GetString("ALLOWEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLOW PRINT.
        /// </summary>
        public static string ALLOWPRINT {
            get {
                return ResourceManager.GetString("ALLOWPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application has been developed to facilitate scanning and document tracking..
        /// </summary>
        public static string APPDESC {
            get {
                return ResourceManager.GetString("APPDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY.
        /// </summary>
        public static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE COLOR.
        /// </summary>
        public static string APPLYCOLOR {
            get {
                return ResourceManager.GetString("APPLYCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is already running..
        /// </summary>
        public static string APPRUNNING {
            get {
                return ResourceManager.GetString("APPRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATIC.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Auto Save Folder.
        /// </summary>
        public static string AUTOFOLDER {
            get {
                return ResourceManager.GetString("AUTOFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Save Path Changed. Old Files Will Not Be Moved To The Newly Determined Folder..
        /// </summary>
        public static string AUTOFOLDERCHANGE {
            get {
                return ResourceManager.GetString("AUTOFOLDERCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTO SCAN
        ///PATH.
        /// </summary>
        public static string AUTOPATH {
            get {
                return ResourceManager.GetString("AUTOPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATIC PICTURE.
        /// </summary>
        public static string AutoPicture {
            get {
                return ResourceManager.GetString("AutoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTO ROTATE.
        /// </summary>
        public static string AUTOROTATE {
            get {
                return ResourceManager.GetString("AUTOROTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATIC TEXT.
        /// </summary>
        public static string AutoText {
            get {
                return ResourceManager.GetString("AutoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATCH.
        /// </summary>
        public static string BATCH {
            get {
                return ResourceManager.GetString("BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Image Files are Added to the Folder Specified Below, Automatic Conversion to Pdf Files in the Same Folder is Made as Long as the Program is Open.
        /// </summary>
        public static string BATCHDESC {
            get {
                return ResourceManager.GetString("BATCHDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATIC BORDER DETECT.
        /// </summary>
        public static string BORDERDETECT {
            get {
                return ResourceManager.GetString("BORDERDETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLACK / WHITE.
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALENDAR.
        /// </summary>
        public static string CALENDAR {
            get {
                return ResourceManager.GetString("CALENDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMERA.
        /// </summary>
        public static string CAMERA {
            get {
                return ResourceManager.GetString("CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR LIST.
        /// </summary>
        public static string CLEARLIST {
            get {
                return ResourceManager.GetString("CLEARLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE COMPUTER.
        /// </summary>
        public static string CLOSECOMP {
            get {
                return ResourceManager.GetString("CLOSECOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLOR.
        /// </summary>
        public static string COLOR {
            get {
                return ResourceManager.GetString("COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If You Click This After Setting the Threshold Value, You Can Make a Second Color Selection..
        /// </summary>
        public static string COLORCHANGETIP {
            get {
                return ResourceManager.GetString("COLORCHANGETIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPRESS.
        /// </summary>
        public static string COMPRESS {
            get {
                return ResourceManager.GetString("COMPRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTENT.
        /// </summary>
        public static string CONTENT {
            get {
                return ResourceManager.GetString("CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since the tesseract and leptonica binaries are compiled with Visual Studio 2019, you need to make sure you have the Visual Studio 2019 Runtime installed.
        /// </summary>
        public static string CRUNTIME {
            get {
                return ResourceManager.GetString("CRUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DAY].
        /// </summary>
        public static string DAY {
            get {
                return ResourceManager.GetString("DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string DEFAULTSCANNAME {
            get {
                return ResourceManager.GetString("DEFAULTSCANNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESKEW.
        /// </summary>
        public static string DESKEW {
            get {
                return ResourceManager.GetString("DESKEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESTINATION LANGUAGE.
        /// </summary>
        public static string DESTLANG {
            get {
                return ResourceManager.GetString("DESTLANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENT.
        /// </summary>
        public static string DOCUMENT {
            get {
                return ResourceManager.GetString("DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAW TEXT.
        /// </summary>
        public static string DRAWTEXT {
            get {
                return ResourceManager.GetString("DRAWTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESTINATION COLOR.
        /// </summary>
        public static string DSTCOLOR {
            get {
                return ResourceManager.GetString("DSTCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIP EMPTY PAGE.
        /// </summary>
        public static string EMPTYPAGE {
            get {
                return ResourceManager.GetString("EMPTYPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENCRYPT.
        /// </summary>
        public static string ENCRYPT {
            get {
                return ResourceManager.GetString("ENCRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Eyp Files Directly..
        /// </summary>
        public static string EYPOPEN {
            get {
                return ResourceManager.GetString("EYPOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAST
        ///SCAN.
        /// </summary>
        public static string FASTSCAN {
            get {
                return ResourceManager.GetString("FASTSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Fast Scan Job.
        /// </summary>
        public static string FASTSCANAFTER {
            get {
                return ResourceManager.GetString("FASTSCANAFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE.
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE NAME:.
        /// </summary>
        public static string FILENAME {
            get {
                return ResourceManager.GetString("FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLATBED.
        /// </summary>
        public static string FLATBED {
            get {
                return ResourceManager.GetString("FLATBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FONT.
        /// </summary>
        public static string FONT {
            get {
                return ResourceManager.GetString("FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAPH.
        /// </summary>
        public static string GRAPH {
            get {
                return ResourceManager.GetString("GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAY.
        /// </summary>
        public static string GRAY {
            get {
                return ResourceManager.GetString("GRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW GUI.
        /// </summary>
        public static string GUI {
            get {
                return ResourceManager.GetString("GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GUID].
        /// </summary>
        public static string GUID {
            get {
                return ResourceManager.GetString("GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEIGHT COUNT.
        /// </summary>
        public static string HEIGHTCOUNT {
            get {
                return ResourceManager.GetString("HEIGHTCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG QUALITY.
        /// </summary>
        public static string JPEGQUALITY {
            get {
                return ResourceManager.GetString("JPEGQUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEFT.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This File Format Has Limited Support..
        /// </summary>
        public static string LIMITED {
            get {
                return ResourceManager.GetString("LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Scanned Documents in the Top List Will Be Deleted Do you want to continue?.
        /// </summary>
        public static string LISTREMOVEWARN {
            get {
                return ResourceManager.GetString("LISTREMOVEWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAD.
        /// </summary>
        public static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE.
        /// </summary>
        public static string MERGE {
            get {
                return ResourceManager.GetString("MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE PDF.
        /// </summary>
        public static string MERGEPDF {
            get {
                return ResourceManager.GetString("MERGEPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE SELECTED
        ///PDF.
        /// </summary>
        public static string MERGESELECTED {
            get {
                return ResourceManager.GetString("MERGESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MINUTE].
        /// </summary>
        public static string MINUTE {
            get {
                return ResourceManager.GetString("MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MONTH].
        /// </summary>
        public static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ACTION.
        /// </summary>
        public static string NO_ACTION {
            get {
                return ResourceManager.GetString("NO ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Patch Code Detected.
        /// </summary>
        public static string NOPATCHCODE {
            get {
                return ResourceManager.GetString("NOPATCHCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO PROFILE SELECTED.
        /// </summary>
        public static string NOPROFILE {
            get {
                return ResourceManager.GetString("NOPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR.
        /// </summary>
        public static string OCR {
            get {
                return ResourceManager.GetString("OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE OCR PDF.
        /// </summary>
        public static string OCRPDFSAVE {
            get {
                return ResourceManager.GetString("OCRPDFSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Ocr Process Takes Extra Time..
        /// </summary>
        public static string OCRTIME {
            get {
                return ResourceManager.GetString("OCRTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY OTHER APPS.
        /// </summary>
        public static string OTHERAPPS {
            get {
                return ResourceManager.GetString("OTHERAPPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER SETTINGS.
        /// </summary>
        public static string OTHERSETTINGS {
            get {
                return ResourceManager.GetString("OTHERSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also download other language data files for tesseract 4.1.0 from tesseract-ocr if needed. Put it in the tessdata folder..
        /// </summary>
        public static string OTHERTESSERACT {
            get {
                return ResourceManager.GetString("OTHERTESSERACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other tesseract language data.
        /// </summary>
        public static string OTHERTESSERACTLINK {
            get {
                return ResourceManager.GetString("OTHERTESSERACTLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directly Overwrite Compressed File in Scanned Documents.
        /// </summary>
        public static string OVERWRITECOMPRESSED {
            get {
                return ResourceManager.GetString("OVERWRITECOMPRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGE NUMBER.
        /// </summary>
        public static string PAGENUMBER {
            get {
                return ResourceManager.GetString("PAGENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Pdf Files Directly..
        /// </summary>
        public static string PDFOPEN {
            get {
                return ResourceManager.GetString("PDFOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF PROTECT.
        /// </summary>
        public static string PDFPROTECT {
            get {
                return ResourceManager.GetString("PDFPROTECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WATCH PDF FOLDER CHANGE.
        /// </summary>
        public static string PDFTRACK {
            get {
                return ResourceManager.GetString("PDFTRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE SETTINGS MADE HERE AFFECT ALL PDF RECORDINGS. 
        ///ALSO PDF PROTECTION CAN BE BROKEN BY 3rd PARTY APPLICATIONS..
        /// </summary>
        public static string PDFWARN {
            get {
                return ResourceManager.GetString("PDFWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVIEW  FILE.
        /// </summary>
        public static string PREVIEWFILE {
            get {
                return ResourceManager.GetString("PREVIEWFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE PREVIEW SIZE.
        /// </summary>
        public static string PREVIEWSIZE {
            get {
                return ResourceManager.GetString("PREVIEWSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETECT QR.
        /// </summary>
        public static string QRDETECT {
            get {
                return ResourceManager.GetString("QRDETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ ACTIVE
        ///PAGE.
        /// </summary>
        public static string READACTIVEPAGE {
            get {
                return ResourceManager.GetString("READACTIVEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER STI
        ///DEVICE.
        /// </summary>
        public static string REGSTI {
            get {
                return ResourceManager.GetString("REGSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Processed Files From Document List.
        /// </summary>
        public static string REMOVEPROCESSEDIMAGE {
            get {
                return ResourceManager.GetString("REMOVEPROCESSEDIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want to Delete the Selected Image?.
        /// </summary>
        public static string REMOVESELECTED {
            get {
                return ResourceManager.GetString("REMOVESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Pages.
        /// </summary>
        public static string REPLACEPAGE {
            get {
                return ResourceManager.GetString("REPLACEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOLUTİON.
        /// </summary>
        public static string RES {
            get {
                return ResourceManager.GetString("RES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTARTAPP.
        /// </summary>
        public static string RESTARTAPP {
            get {
                return ResourceManager.GetString("RESTARTAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTART COMPUTER.
        /// </summary>
        public static string RESTARTCOMP {
            get {
                return ResourceManager.GetString("RESTARTCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVERSE.
        /// </summary>
        public static string REVERSE {
            get {
                return ResourceManager.GetString("REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIGHT.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROTATE 180 DEGREES.
        /// </summary>
        public static string Rotate180 {
            get {
                return ResourceManager.GetString("Rotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROTATE 270 DEGREES.
        /// </summary>
        public static string Rotate270 {
            get {
                return ResourceManager.GetString("Rotate270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROTATE 90 DEGREES.
        /// </summary>
        public static string Rotate90 {
            get {
                return ResourceManager.GetString("Rotate90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Rotation.
        /// </summary>
        public static string ROTSAVE {
            get {
                return ResourceManager.GetString("ROTSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE PDF.
        /// </summary>
        public static string SAVEPDF {
            get {
                return ResourceManager.GetString("SAVEPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE PROFILE.
        /// </summary>
        public static string SAVEPROFILE {
            get {
                return ResourceManager.GetString("SAVEPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE SELECTED.
        /// </summary>
        public static string SAVESELECTED {
            get {
                return ResourceManager.GetString("SAVESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCAN.
        /// </summary>
        public static string SCAN {
            get {
                return ResourceManager.GetString("SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCANNER.
        /// </summary>
        public static string SCANNER {
            get {
                return ResourceManager.GetString("SCANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SECOND].
        /// </summary>
        public static string SECOND {
            get {
                return ResourceManager.GetString("SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AT LEAST TWO PDF FILE.
        /// </summary>
        public static string SELECTTWOPDF {
            get {
                return ResourceManager.GetString("SELECTTWOPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPERATE SCAN.
        /// </summary>
        public static string SEPERATESCAN {
            get {
                return ResourceManager.GetString("SEPERATESCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Each Page to Separate File Files are Saved to the Folder Specified Below..
        /// </summary>
        public static string SEPERATESCANTOOLTIP {
            get {
                return ResourceManager.GetString("SEPERATESCANTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE SEPERATOR.
        /// </summary>
        public static string SEPERATOR {
            get {
                return ResourceManager.GetString("SEPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SETTİNGS {
            get {
                return ResourceManager.GetString("SETTİNGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW FILE AFTER FAST SCAN.
        /// </summary>
        public static string SHOWFILE {
            get {
                return ResourceManager.GetString("SHOWFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW IN FOLDER.
        /// </summary>
        public static string SHOWFOLDER {
            get {
                return ResourceManager.GetString("SHOWFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW PROGRESS.
        /// </summary>
        public static string SHOWPROGRESS {
            get {
                return ResourceManager.GetString("SHOWPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLICE.
        /// </summary>
        public static string SLICE {
            get {
                return ResourceManager.GetString("SLICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE LANGUAGE.
        /// </summary>
        public static string SOURCELANG {
            get {
                return ResourceManager.GetString("SOURCELANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitted.
        /// </summary>
        public static string SPLIT {
            get {
                return ResourceManager.GetString("SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click To Restore, Right Click To Expand.
        /// </summary>
        public static string SPLITTERTOOLTIP {
            get {
                return ResourceManager.GetString("SPLITTERTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SOURCE.
        /// </summary>
        public static string SRC {
            get {
                return ResourceManager.GetString("SRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE COLOR.
        /// </summary>
        public static string SRCCOLOR {
            get {
                return ResourceManager.GetString("SRCCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click to select source color..
        /// </summary>
        public static string SRCCOLORTIP {
            get {
                return ResourceManager.GetString("SRCCOLORTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAG.
        /// </summary>
        public static string TAG {
            get {
                return ResourceManager.GetString("TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Tasks Are Running Wait For It To Finish..
        /// </summary>
        public static string TASKSRUNNING {
            get {
                return ResourceManager.GetString("TASKSRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESSERACT.
        /// </summary>
        public static string TESSERACT {
            get {
                return ResourceManager.GetString("TESSERACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tesseract Language.
        /// </summary>
        public static string TESSLANGSELECT {
            get {
                return ResourceManager.GetString("TESSLANGSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT ANGLE.
        /// </summary>
        public static string TEXTANGLE {
            get {
                return ResourceManager.GetString("TEXTANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT SIZE.
        /// </summary>
        public static string TEXTSIZE {
            get {
                return ResourceManager.GetString("TEXTSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd PARTY LIBRARIES USED IN THE APPLICATION.
        /// </summary>
        public static string THIRDPARTY {
            get {
                return ResourceManager.GetString("THIRDPARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THRESHOLD.
        /// </summary>
        public static string THRESHOLD {
            get {
                return ResourceManager.GetString("THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TIME].
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSLATE.
        /// </summary>
        public static string TRANSLATE {
            get {
                return ResourceManager.GetString("TRANSLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Process is in Progress. Wait for it to finish..
        /// </summary>
        public static string TRANSLATEPENDING {
            get {
                return ResourceManager.GetString("TRANSLATEPENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIM IMAGE.
        /// </summary>
        public static string TRIMIMAGE {
            get {
                return ResourceManager.GetString("TRIMIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWO SIDE.
        /// </summary>
        public static string TWOSIDE {
            get {
                return ResourceManager.GetString("TWOSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNREGISTER STI DEVICE.
        /// </summary>
        public static string UNREGSTI {
            get {
                return ResourceManager.GetString("UNREGSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERNAME].
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2019 x86 and x64 Runtimes.
        /// </summary>
        public static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW ALL.
        /// </summary>
        public static string VIEWALL {
            get {
                return ResourceManager.GetString("VIEWALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown Or Restart Is Set..
        /// </summary>
        public static string WARNREBOOT {
            get {
                return ResourceManager.GetString("WARNREBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WATERMARK.
        /// </summary>
        public static string WATERMARK {
            get {
                return ResourceManager.GetString("WATERMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIDTH COUNT.
        /// </summary>
        public static string WIDTHCOUNT {
            get {
                return ResourceManager.GetString("WIDTHCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [YEAR].
        /// </summary>
        public static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
    }
}
