//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwainControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_cs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_cs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwainControl.Properties.Resources.cs", typeof(Resources_cs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O NÁS.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PŘILOŽTE DOKUMENTY K SOUBORU.
        /// </summary>
        public static string ADDDOC {
            get {
                return ResourceManager.GetString("ADDDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULOŽIT DATA OCR.
        /// </summary>
        public static string ADDOCRTODB {
            get {
                return ResourceManager.GetString("ADDOCRTODB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud je zaškrtnuto, text aktivního dokumentu vlevo se uloží do databáze..
        /// </summary>
        public static string ADDOCRTOOLTIP {
            get {
                return ResourceManager.GetString("ADDOCRTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PODAVAČ
        ///DOKUMENTŮ.
        /// </summary>
        public static string ADF {
            get {
                return ResourceManager.GetString("ADF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkem.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POVOLIT KOPÍROVÁNÍ OBSAHU.
        /// </summary>
        public static string ALLOWCOPY {
            get {
                return ResourceManager.GetString("ALLOWCOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POVOLIT EDITACI DOKUMENTU.
        /// </summary>
        public static string ALLOWEDIT {
            get {
                return ResourceManager.GetString("ALLOWEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POVOLIT TISK.
        /// </summary>
        public static string ALLOWPRINT {
            get {
                return ResourceManager.GetString("ALLOWPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tato aplikace byla vyvinuta pro usnadnění skenování a sledování dokumentů.
        /// </summary>
        public static string APPDESC {
            get {
                return ResourceManager.GetString("APPDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použít.
        /// </summary>
        public static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POUŽÍT BARVU.
        /// </summary>
        public static string APPLYCOLOR {
            get {
                return ResourceManager.GetString("APPLYCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikace je již spuštěna.
        /// </summary>
        public static string APPRUNNING {
            get {
                return ResourceManager.GetString("APPRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATICKY.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadat automatické uložení složky..
        /// </summary>
        public static string AUTOFOLDER {
            get {
                return ResourceManager.GetString("AUTOFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automaticky uložená cesta změněna. Staré soubory nebudou přesunuty do nové složky..
        /// </summary>
        public static string AUTOFOLDERCHANGE {
            get {
                return ResourceManager.GetString("AUTOFOLDERCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATICKÉ
        ///ULOŽENÍ.
        /// </summary>
        public static string AUTOPATH {
            get {
                return ResourceManager.GetString("AUTOPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTO-PICTURE.
        /// </summary>
        public static string AutoPicture {
            get {
                return ResourceManager.GetString("AutoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATICKÉ OTÁČENÍ.
        /// </summary>
        public static string AUTOROTATE {
            get {
                return ResourceManager.GetString("AUTOROTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATICKÝ TEXT.
        /// </summary>
        public static string AutoText {
            get {
                return ResourceManager.GetString("AutoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOLEKTIVNÍ PRÁCE.
        /// </summary>
        public static string BATCH {
            get {
                return ResourceManager.GetString("BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Když jsou soubory obrázků přidány do složky níže, provádí se automatický překlad do souboru PDF ve stejné složce, dokud je program otevřen.
        /// </summary>
        public static string BATCHDESC {
            get {
                return ResourceManager.GetString("BATCHDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATICKÁ DETEKCE HRAN.
        /// </summary>
        public static string BORDERDETECT {
            get {
                return ResourceManager.GetString("BORDERDETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ČERNOBÍLE.
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KALENDÁŘ.
        /// </summary>
        public static string CALENDAR {
            get {
                return ResourceManager.GetString("CALENDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamera.
        /// </summary>
        public static string CAMERA {
            get {
                return ResourceManager.GetString("CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VYČISTĚTE SEZNAM.
        /// </summary>
        public static string CLEARLIST {
            get {
                return ResourceManager.GetString("CLEARLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VYPNĚTE POČÍTAČ.
        /// </summary>
        public static string CLOSECOMP {
            get {
                return ResourceManager.GetString("CLOSECOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAREVNÉ.
        /// </summary>
        public static string COLOR {
            get {
                return ResourceManager.GetString("COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud na něj kliknete po nastavení prahové hodnoty, můžete zvolit druhou barvu.
        /// </summary>
        public static string COLORCHANGETIP {
            get {
                return ResourceManager.GetString("COLORCHANGETIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZMÁČKNI TO.
        /// </summary>
        public static string COMPRESS {
            get {
                return ResourceManager.GetString("COMPRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÁPOJE SE ČTOU.
        /// </summary>
        public static string CONTENT {
            get {
                return ResourceManager.GetString("CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vzhledem k tomu, že binární soubory Tesseract a leptonica jsou kompilovány s Visual Studio 2019, musíte se ujistit, že je nainstalován Visual Studio 2019 Runtime.
        /// </summary>
        public static string CRUNTIME {
            get {
                return ResourceManager.GetString("CRUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEN].
        /// </summary>
        public static string DAY {
            get {
                return ResourceManager.GetString("DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÝCHOZÍ.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neskenujte.
        /// </summary>
        public static string DEFAULTSCANNAME {
            get {
                return ResourceManager.GetString("DEFAULTSCANNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMAZAT.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPRAVTE ZAKŘIVENÍ.
        /// </summary>
        public static string DESKEW {
            get {
                return ResourceManager.GetString("DESKEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÍLOVÁ ŘEČ.
        /// </summary>
        public static string DESTLANG {
            get {
                return ResourceManager.GetString("DESTLANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAPÍROVÁNÍ.
        /// </summary>
        public static string DOCUMENT {
            get {
                return ResourceManager.GetString("DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAKRESLETE TEXT.
        /// </summary>
        public static string DRAWTEXT {
            get {
                return ResourceManager.GetString("DRAWTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÍLOVÁ BARVA.
        /// </summary>
        public static string DSTCOLOR {
            get {
                return ResourceManager.GetString("DSTCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PŘESKOČTE PRÁZDNÉ STRÁNKY.
        /// </summary>
        public static string EMPTYPAGE {
            get {
                return ResourceManager.GetString("EMPTYPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŠIFROVAT.
        /// </summary>
        public static string ENCRYPT {
            get {
                return ResourceManager.GetString("ENCRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřete soubory EYP přímo.
        /// </summary>
        public static string EYPOPEN {
            get {
                return ResourceManager.GetString("EYPOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RYCHLÉ
        ///SKENOVÁNÍ.
        /// </summary>
        public static string FASTSCAN {
            get {
                return ResourceManager.GetString("FASTSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce, která má být provedena po dokončení rychlého skenování.
        /// </summary>
        public static string FASTSCANAFTER {
            get {
                return ResourceManager.GetString("FASTSCANAFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor.
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÁZEV SOUBORU:.
        /// </summary>
        public static string FILENAME {
            get {
                return ResourceManager.GetString("FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FIX {
            get {
                return ResourceManager.GetString("FIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLOCHÁ POSTEL.
        /// </summary>
        public static string FLATBED {
            get {
                return ResourceManager.GetString("FLATBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PÍSMO.
        /// </summary>
        public static string FONT {
            get {
                return ResourceManager.GetString("FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAFIKA.
        /// </summary>
        public static string GRAPH {
            get {
                return ResourceManager.GetString("GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAYI.
        /// </summary>
        public static string GRAY {
            get {
                return ResourceManager.GetString("GRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOBRAZIT ROZHRANÍ.
        /// </summary>
        public static string GUI {
            get {
                return ResourceManager.GetString("GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GUID].
        /// </summary>
        public static string GUID {
            get {
                return ResourceManager.GetString("GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POČET VÝŠEK.
        /// </summary>
        public static string HEIGHTCOUNT {
            get {
                return ResourceManager.GetString("HEIGHTCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RYCHLOST KVALITY JPEG.
        /// </summary>
        public static string JPEGQUALITY {
            get {
                return ResourceManager.GetString("JPEGQUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zbývá.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tento formát souboru má omezenou podporu..
        /// </summary>
        public static string LIMITED {
            get {
                return ResourceManager.GetString("LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny naskenované dokumenty ve výše uvedeném seznamu budou smazány. Chcete pokračovat?.
        /// </summary>
        public static string LISTREMOVEWARN {
            get {
                return ResourceManager.GetString("LISTREMOVEWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naинst.
        /// </summary>
        public static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEJ TO DOHROMADY.
        /// </summary>
        public static string MERGE {
            get {
                return ResourceManager.GetString("MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLOUČIT PDF.
        /// </summary>
        public static string MERGEPDF {
            get {
                return ResourceManager.GetString("MERGEPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLOUČIT OZNAČENÉ
        ///SOUBORY PDF.
        /// </summary>
        public static string MERGESELECTED {
            get {
                return ResourceManager.GetString("MERGESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MINUTY].
        /// </summary>
        public static string MINUTE {
            get {
                return ResourceManager.GetString("MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MONTH].
        /// </summary>
        public static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŽÁDNÁ AKCE.
        /// </summary>
        public static string NO_ACTION {
            get {
                return ResourceManager.GetString("NO ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIKDO Z NICH.
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kód opravy nebyl zjištěn.
        /// </summary>
        public static string NOPATCHCODE {
            get {
                return ResourceManager.GetString("NOPATCHCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEBYL VYBRÁN ŽÁDNÝ PROFIL.
        /// </summary>
        public static string NOPROFILE {
            get {
                return ResourceManager.GetString("NOPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR.
        /// </summary>
        public static string OCR {
            get {
                return ResourceManager.GetString("OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULOŽIT OCR PDF.
        /// </summary>
        public static string OCRPDFSAVE {
            get {
                return ResourceManager.GetString("OCRPDFSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf OCR trvá hodně času.
        /// </summary>
        public static string OCRTIME {
            get {
                return ResourceManager.GetString("OCRTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOJE DALŠÍ APLIKACE.
        /// </summary>
        public static string OTHERAPPS {
            get {
                return ResourceManager.GetString("OTHERAPPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DALŠÍ NASTAVENÍ.
        /// </summary>
        public static string OTHERSETTINGS {
            get {
                return ResourceManager.GetString("OTHERSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V případě potřeby stáhněte také další jazykové datové soubory pro tesseract 4.1.0 z tesseract-ocr. Dejte to do složky Tessdata.
        /// </summary>
        public static string OTHERTESSERACT {
            get {
                return ResourceManager.GetString("OTHERTESSERACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Další tesseract jazyková data.
        /// </summary>
        public static string OTHERTESSERACTLINK {
            get {
                return ResourceManager.GetString("OTHERTESSERACTLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přepsat komprimovaný soubor v naskenovaných dokumentech přímo.
        /// </summary>
        public static string OVERWRITECOMPRESSED {
            get {
                return ResourceManager.GetString("OVERWRITECOMPRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRANA Č..
        /// </summary>
        public static string PAGENUMBER {
            get {
                return ResourceManager.GetString("PAGENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HESLO.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřete soubory PDF přímo..
        /// </summary>
        public static string PDFOPEN {
            get {
                return ResourceManager.GetString("PDFOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Protect.
        /// </summary>
        public static string PDFPROTECT {
            get {
                return ResourceManager.GetString("PDFPROTECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PODÍVEJTE SE NA ZMĚNU SLOŽKY PDF.
        /// </summary>
        public static string PDFTRACK {
            get {
                return ResourceManager.GetString("PDFTRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZDE PROVEDENÁ NASTAVENÍ OVLIVŇUJÍ VŠECHNY ZÁZNAMY PDF.
        ///TAKÉ OCHRANA PDF MŮŽE BÝT PORUŠENA APLIKACEMI TŘETÍCH STRAN..
        /// </summary>
        public static string PDFWARN {
            get {
                return ResourceManager.GetString("PDFWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÁHLED SOUBORU.
        /// </summary>
        public static string PREVIEWFILE {
            get {
                return ResourceManager.GetString("PREVIEWFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VELIKOST NÁHLEDU OBRÁZKU.
        /// </summary>
        public static string PREVIEWSIZE {
            get {
                return ResourceManager.GetString("PREVIEWSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETEKUJTE QR.
        /// </summary>
        public static string QRDETECT {
            get {
                return ResourceManager.GetString("QRDETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PŘEČTĚTE SI AKTIVNÍ STRÁNKU.
        /// </summary>
        public static string READACTIVEPAGE {
            get {
                return ResourceManager.GetString("READACTIVEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PŘIDAT DO MENU PROHLÍŽEČE.
        /// </summary>
        public static string REGSTI {
            get {
                return ResourceManager.GetString("REGSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat zpracované soubory ze seznamu dokumentů.
        /// </summary>
        public static string REMOVEPROCESSEDIMAGE {
            get {
                return ResourceManager.GetString("REMOVEPROCESSEDIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete smazat vybraný obrázek?.
        /// </summary>
        public static string REMOVESELECTED {
            get {
                return ResourceManager.GetString("REMOVESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahradit stránky.
        /// </summary>
        public static string REPLACEPAGE {
            get {
                return ResourceManager.GetString("REPLACEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROZLIŠENÍ.
        /// </summary>
        public static string RES {
            get {
                return ResourceManager.GetString("RES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikaci je třeba restartovat.
        /// </summary>
        public static string RESTARTAPP {
            get {
                return ResourceManager.GetString("RESTARTAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTARTUJTE POČÍTAČ.
        /// </summary>
        public static string RESTARTCOMP {
            get {
                return ResourceManager.GetString("RESTARTCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZPÁTEČKA.
        /// </summary>
        public static string REVERSE {
            get {
                return ResourceManager.GetString("REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šipka doprava.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTOČIT O 180 STUPŇŮ.
        /// </summary>
        public static string Rotate180 {
            get {
                return ResourceManager.GetString("Rotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTOČIT O 270 STUPŇŮ.
        /// </summary>
        public static string Rotate270 {
            get {
                return ResourceManager.GetString("Rotate270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTOČIT O 90 STUPŇŮ.
        /// </summary>
        public static string Rotate90 {
            get {
                return ResourceManager.GetString("Rotate90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ušetřete s Rotation Applied?.
        /// </summary>
        public static string ROTSAVE {
            get {
                return ResourceManager.GetString("ROTSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string SAVEPDF {
            get {
                return ResourceManager.GetString("SAVEPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKRÝT PROFIL.
        /// </summary>
        public static string SAVEPROFILE {
            get {
                return ResourceManager.GetString("SAVEPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZACHRAŇTE VÝBĚRY.
        /// </summary>
        public static string SAVESELECTED {
            get {
                return ResourceManager.GetString("SAVESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledat.
        /// </summary>
        public static string SCAN {
            get {
                return ResourceManager.GetString("SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKENER.
        /// </summary>
        public static string SCANNER {
            get {
                return ResourceManager.GetString("SCANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SEKUNDY].
        /// </summary>
        public static string SECOND {
            get {
                return ResourceManager.GetString("SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VYBERTE ALESPOŇ DVA SOUBORY PDF.
        /// </summary>
        public static string SELECTTWOPDF {
            get {
                return ResourceManager.GetString("SELECTTWOPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKENUJTE KAŽDOU STRÁNKU ZVLÁŠŤ.
        /// </summary>
        public static string SEPERATESCAN {
            get {
                return ResourceManager.GetString("SEPERATESCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Každá stránka se uloží do samostatného souboru Soubory se uloží do níže uvedené složky..
        /// </summary>
        public static string SEPERATESCANTOOLTIP {
            get {
                return ResourceManager.GetString("SEPERATESCANTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oddělovač.
        /// </summary>
        public static string SEPERATOR {
            get {
                return ResourceManager.GetString("SEPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASTAVENÍ.
        /// </summary>
        public static string SETTİNGS {
            get {
                return ResourceManager.GetString("SETTİNGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOBRAZIT SOUBOR PO RYCHLÉM SKENOVÁNÍ.
        /// </summary>
        public static string SHOWFILE {
            get {
                return ResourceManager.GetString("SHOWFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOBRAZIT VE SLOŽCE.
        /// </summary>
        public static string SHOWFOLDER {
            get {
                return ResourceManager.GetString("SHOWFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UKAŽTE MI PROCENTO.
        /// </summary>
        public static string SHOWPROGRESS {
            get {
                return ResourceManager.GetString("SHOWPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROZBIJ TO.
        /// </summary>
        public static string SLICE {
            get {
                return ResourceManager.GetString("SLICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZDROJOVÝ JAZYK.
        /// </summary>
        public static string SOURCELANG {
            get {
                return ResourceManager.GetString("SOURCELANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je to rozbité.
        /// </summary>
        public static string SPLIT {
            get {
                return ResourceManager.GetString("SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dvakrát klikněte pro obnovení, klikněte pravým tlačítkem myši pro rozbalení.
        /// </summary>
        public static string SPLITTERTOOLTIP {
            get {
                return ResourceManager.GetString("SPLITTERTOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VYBERTE ZDROJ.
        /// </summary>
        public static string SRC {
            get {
                return ResourceManager.GetString("SRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARVA ZDROJE.
        /// </summary>
        public static string SRCCOLOR {
            get {
                return ResourceManager.GetString("SRCCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klikněte pravým tlačítkem myši a vyberte si barvu.
        /// </summary>
        public static string SRCCOLORTIP {
            get {
                return ResourceManager.GetString("SRCCOLORTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spustit.
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŠTÍTEK.
        /// </summary>
        public static string TAG {
            get {
                return ResourceManager.GetString("TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počkejte na dokončení některých úkolů.
        /// </summary>
        public static string TASKSRUNNING {
            get {
                return ResourceManager.GetString("TASKSRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESSERACT.
        /// </summary>
        public static string TESSERACT {
            get {
                return ResourceManager.GetString("TESSERACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte jazyk Tesseract.
        /// </summary>
        public static string TESSLANGSELECT {
            get {
                return ResourceManager.GetString("TESSLANGSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METINE.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÚHEL TEXTU.
        /// </summary>
        public static string TEXTANGLE {
            get {
                return ResourceManager.GetString("TEXTANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VELIKOST TEXTU.
        /// </summary>
        public static string TEXTSIZE {
            get {
                return ResourceManager.GetString("TEXTSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KNIHOVNY TŘETÍCH STRAN POUŽÍVANÉ V PRAXI.
        /// </summary>
        public static string THIRDPARTY {
            get {
                return ResourceManager.GetString("THIRDPARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRAHOVÁ HODNOTA.
        /// </summary>
        public static string THRESHOLD {
            get {
                return ResourceManager.GetString("THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodiny.
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PŘEKLAD.
        /// </summary>
        public static string TRANSLATE {
            get {
                return ResourceManager.GetString("TRANSLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operace probíhá, počkejte, až to skončí.
        /// </summary>
        public static string TRANSLATEPENDING {
            get {
                return ResourceManager.GetString("TRANSLATEPENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OŘÍZNOUT OBRÁZEK.
        /// </summary>
        public static string TRIMIMAGE {
            get {
                return ResourceManager.GetString("TRIMIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBOUSMĚRNĚ.
        /// </summary>
        public static string TWOSIDE {
            get {
                return ResourceManager.GetString("TWOSIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODEBRAT Z NABÍDKY PROHLÍŽEČE.
        /// </summary>
        public static string UNREGSTI {
            get {
                return ResourceManager.GetString("UNREGSTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizace.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UŽIVATELSKÉ JMÉNO].
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2019 x86 a x64 Runtime.
        /// </summary>
        public static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOBRAZIT VŠE.
        /// </summary>
        public static string VIEWALL {
            get {
                return ResourceManager.GetString("VIEWALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypnout nebo restartovat nastavení!.
        /// </summary>
        public static string WARNREBOOT {
            get {
                return ResourceManager.GetString("WARNREBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VODOZNAK.
        /// </summary>
        public static string WATERMARK {
            get {
                return ResourceManager.GetString("WATERMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POČET NEJVÍCE.
        /// </summary>
        public static string WIDTHCOUNT {
            get {
                return ResourceManager.GetString("WIDTHCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ROK].
        /// </summary>
        public static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
    }
}
