//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwainControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double Çözünürlük {
            get {
                return ((double)(this["Çözünürlük"]));
            }
            set {
                this["Çözünürlük"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoFolder {
            get {
                return ((string)(this["AutoFolder"]));
            }
            set {
                this["AutoFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Adf {
            get {
                return ((bool)(this["Adf"]));
            }
            set {
                this["Adf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFile {
            get {
                return ((bool)(this["ShowFile"]));
            }
            set {
                this["ShowFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Mode {
            get {
                return ((int)(this["Mode"]));
            }
            set {
                this["Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DateGroupFolder {
            get {
                return ((bool)(this["DateGroupFolder"]));
            }
            set {
                this["DateGroupFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("155")]
        public double PreviewWidth {
            get {
                return ((double)(this["PreviewWidth"]));
            }
            set {
                this["PreviewWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultProfile {
            get {
                return ((string)(this["DefaultProfile"]));
            }
            set {
                this["DefaultProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EmptyThreshold {
            get {
                return ((int)(this["EmptyThreshold"]));
            }
            set {
                this["EmptyThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSelectedProfile {
            get {
                return ((bool)(this["UseSelectedProfile"]));
            }
            set {
                this["UseSelectedProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ImgLoadResolution {
            get {
                return ((int)(this["ImgLoadResolution"]));
            }
            set {
                this["ImgLoadResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int JpegQuality {
            get {
                return ((int)(this["JpegQuality"]));
            }
            set {
                this["JpegQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DefaultPictureResizeRatio {
            get {
                return ((int)(this["DefaultPictureResizeRatio"]));
            }
            set {
                this["DefaultPictureResizeRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int BackMode {
            get {
                return ((int)(this["BackMode"]));
            }
            set {
                this["BackMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d.MM.yyyy")]
        public string FolderDateFormat {
            get {
                return ((string)(this["FolderDateFormat"]));
            }
            set {
                this["FolderDateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveProcessedImage {
            get {
                return ((bool)(this["RemoveProcessedImage"]));
            }
            set {
                this["RemoveProcessedImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int BwThreshold {
            get {
                return ((int)(this["BwThreshold"]));
            }
            set {
                this["BwThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DirectRemoveImage {
            get {
                return ((bool)(this["DirectRemoveImage"]));
            }
            set {
                this["DirectRemoveImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n                <ArrayOfString xmlns:xsd" +
            "=\"http://www.w3.org/2001/XMLSchema\"\r\n                xmlns:xsi=\"http://www.w3.or" +
            "g/2001/XMLSchema-instance\" />\r\n            ")]
        public global::System.Collections.Specialized.StringCollection Profile {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Profile"]));
            }
            set {
                this["Profile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n                <ArrayOfString xmlns:xsd" +
            "=\"http://www.w3.org/2001/XMLSchema\"\r\n                xmlns:xsi=\"http://www.w3.or" +
            "g/2001/XMLSchema-instance\" />\r\n            ")]
        public global::System.Collections.Specialized.StringCollection PdfLoadHistory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PdfLoadHistory"]));
            }
            set {
                this["PdfLoadHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MedianValue {
            get {
                return ((int)(this["MedianValue"]));
            }
            set {
                this["MedianValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int WebpQuality {
            get {
                return ((int)(this["WebpQuality"]));
            }
            set {
                this["WebpQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DefaultThumbPictureResizeRatio {
            get {
                return ((int)(this["DefaultThumbPictureResizeRatio"]));
            }
            set {
                this["DefaultThumbPictureResizeRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SeçiliTarayıcı {
            get {
                return ((string)(this["SeçiliTarayıcı"]));
            }
            set {
                this["SeçiliTarayıcı"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoCropImage {
            get {
                return ((bool)(this["AutoCropImage"]));
            }
            set {
                this["AutoCropImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string AutoCropColor {
            get {
                return ((string)(this["AutoCropColor"]));
            }
            set {
                this["AutoCropColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29.7")]
        public double CustomPaperHeight {
            get {
                return ((double)(this["CustomPaperHeight"]));
            }
            set {
                this["CustomPaperHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public double CustomPaperWidth {
            get {
                return ((double)(this["CustomPaperWidth"]));
            }
            set {
                this["CustomPaperWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ScanDelay {
            get {
                return ((double)(this["ScanDelay"]));
            }
            set {
                this["ScanDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayNotificationAudio {
            get {
                return ((bool)(this["PlayNotificationAudio"]));
            }
            set {
                this["PlayNotificationAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioFilePath {
            get {
                return ((string)(this["AudioFilePath"]));
            }
            set {
                this["AudioFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScanSettingsExpanderIsExpanded {
            get {
                return ((bool)(this["ScanSettingsExpanderIsExpanded"]));
            }
            set {
                this["ScanSettingsExpanderIsExpanded"] = value;
            }
        }
    }
}
